language: ruby
rvm:
  - 2.1
install:
  - bundle install
  - npm install
script:
  - bundle exec jekyll build
#whitelist
branches:
  only:
    - master
deploy:
  provider: s3
  access_key_id: $aws_key
  secret_access_key: $aws_secret_key
  bucket: "docs.synapse.org"
  skip_cleanup: true
  on:
    branch: master
    condition: $MY_ENV = if [ -z "$aws_key" ]

