language: ruby
rvm:
  - 2.1
install:
  - bundle install
  - npm install
script:
  - bundle exec jekyll build
#whitelist
branches:
  only:
    - master
#deploy:
#  provider: s3
#  access_key_id: "YOUR AWS ACCESS KEY"
#  secret_access_key: "YOUR AWS SECRET KEY"
#  bucket: "S3 Bucket"
#  skip_cleanup: true

