source:      .
destination: ./_site
plugins_dir:     ./_plugins
include: []
encoding: utf-8
exclude: [bin, CNAME, Gemfile, Gemfile.lock, README.md, Dockerfile, fig.yml, node_modules]
permalink: /:title
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
gems:
    - jekyll-seo-tag

title: Synapse Docs
description: Synapse is an open source software platform that data scientists use to carry out, track, and communicate their research in real time.
url: docs.syanpse.org
author: Sage Bionetworks
logo: ./assets/images/synapse_logo_white_small.png